

Controls = {
  Focus = 185,
  Grab = 24,
}

furni = {}

furni.objects = {
  ["Sofás"] = {
    [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Sofá Florido Antigo" },
    [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "Cadeira de 3 lugares" },
    [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Sofá Antigo de 1 Lugar" },
    [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Sofá Antigo de 3 Lugares" },
    [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Sofá Listrado Antigo" },
    [6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Antigo sofá amarelo de 1 lugar" },
    [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["name"] = "Sofá de canto" },
    [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["name"] = "Sofá de canto 2" },
    [9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Sofá 1" },
    [10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Sofá 2" },
    [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Sofá 3" },
    [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "Sofá 4" },
    [13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Sofá 5" },
    [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Sofá 6" },
    [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Sofá 7" },
    [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Sofá 8" },
    [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Sofá 9" },
    [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Sofá 10" },
    [19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Sofá 11" },
    [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "banquinho 1" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "banquinho 2" },
    [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "banquinho 2" },
  },

  ["Cadeiras"] = {
    [1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "Cadeira alta" },
    [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Cadeira" },
    [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Cadeira" },
    [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "Cadeira alta" },
    [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Cadeira de Jantar 1" },
    [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Cadeira de Jantar 2" },
    [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Cadeira de Jantar 3" },
    [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Cadeira" },
    [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Banco" },
    [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "Cadeira alta" },
    [11] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Cadeirão" },
    [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Cadeira de jantar" },
    [13] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Banco" },
    [14] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "Cadeira MB" },
    [15] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Cadeirão" },
    [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Cadeira de jantar" },
    [17] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Cadeira de Estudo" },
    [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Cadeira de armação" },
    [19] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Cadeira" },
    [20] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Cadeira de escritório" },
    [21] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Banco" },
    [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Banco de couro" },
    [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Banco" },
    [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Cadeira de Mesa" },
    [25] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Poltrona" },
    [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Cadeira de vime" },
    [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Cadeira Diretor 1" },
    [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Cadeira Diretor 2" },
    [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Assento 1 do Iate" },
    [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Assento 2 do Iate" },
    [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Assento 3 do Iate" },
    [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Assento 4 do Iate" },
    [33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "Cadeira Branca" },
    [34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Cadeira" },
    [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "banco TA" },
    [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Cadeira de escritório" },
  },

  ["Camas"] = {
    [1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "Cama D" },  
    [2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "Cama L" }, 
    [3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "Cama MB" }, 
    [4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "Cama MD" }, 
    [5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Cama de Pedreiro" },  
    [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "Cama T" }, 
    [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "Cama T 2" }, 
    [8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "Cama TT" },
    [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 700, ["name"] = "Cama de casal" },  
    [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 700, ["name"] = "Cama de Casal 2" },
    [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 700, ["name"] = "Cama de Casal 3" },
    [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "cama com mesa" },
    [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 500, ["name"] = "Cama de solteiro" },
  },

  ["Geral 1"] = {
    [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Saco de feijão 1" },
    [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "Vaso Branco" },
    [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Parede acolchoada" },
    [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Item" },
    [5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Chicotes" },
    [6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Revistas" },
    [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Revistas abertas" },
    [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Mag arrumado" },
    [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Comida de Yoga 1" },
    [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Comida de Yoga 2" },
    [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Pós-barba" },
    [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Flores" },
    [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "fruteira" },
    [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Cesta de lavanderia" },
    [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "otomano" },
    [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Escultura" },
    [17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Porta-revistas" },
    [18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Caixa de joias" },
    [19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Caixa" },
    [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Tigela ornamentada" },
    [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Vaso de Bronze" },
    [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Quadro de giz" },
    [23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Aparador" },
    [24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
    [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Cinzeiro" },
    [26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Vela" },
    [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Vela Grande" },
    [28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Balanças" },
    [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Travesseiro de Cama" },
    [30] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 300, ["name"] = "Arte da parede 1" },
    [31] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 300, ["name"] = "Arte da parede 2" },
    [32] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Arte da parede 3" },
    [33] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 300, ["name"] = "Arte da parede 4" },
    [34] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 300, ["name"] = "Arte da parede 5" },
    [35] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 300, ["name"] = "Tapete 1" },
    [36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 300, ["name"] = "Tapete 2" },
    [37] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 300, ["name"] = "Tapete 3" },
    [38] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 100, ["name"] = "Objeto de merda" },
  },

  ["Geral 2"] = {
    [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "Ach Frango" },
    [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 onças" },
    [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Cerveja" },
    [4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Aviadores" },
    [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Detalhe" },
    [6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Cervejas" },
    [7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binóculos" },
    [8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Spray Blox" },
    [9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongô" },
    [10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong" },
    [11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Caixa de som" },
    [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Tigela de batatas fritas" },
    [13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Doce" },
    [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Bolsa de transporte" },
    [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Jarro de Cerâmica" },
    [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Pacote de charutos 1" },
    [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Pacote de charutos 2" },
    [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Caixa de cerveja 2" },
    [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Encadernador" },
    [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Xícara" },
    [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
    [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flauta" },
    [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Mochila" },
    [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
    [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "Estojo de DVD" },
    [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Rolo de filme" },
    [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Cego" },
    [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Sacola" },
    [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Tabua de passar" },
    [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
    [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Chaleira" },
    [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Caixa" },
    [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Lata de gasolina" },
    [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Saco" },
    [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Frasco de script" },
    [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Frasco de roteiro 2" },
    [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Saco de lixo" },
    [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Garrafa de Uísque" },
    [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong" },
    [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Amendoim" },
    [41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Copo" },
  },

  ["Geral 3"] = {
    [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "Caixa de CSR" },
    [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Cesta" },
    [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "Bolsa GC 1" },
    [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "Bolsa GC 2" },
    [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "Compartimento GC" },
    [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Caixa registradora" },
    [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "Presidente do GC 01" },
    [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "Presidente do CG 02" },
    [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Relógio" },
    [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
    [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Produção 2" },
    [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
    [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
    [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
    [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
    [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "Unidade HD 1" },
    [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "Unidade HD 2" },
    [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Frigorífico" },
    [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Saco 1" },
    [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bolsa 2" },
    [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Livro 1" },
    [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Livro 2" },
    [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Livro 3" },
    [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Livro 4" },
    [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Câmera" },
    [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "Primeiro socorro" },
    [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Herói" },
    [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Faça 1" },
    [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Faça 2" },
    [30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Crânio" },
    [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Violão" },
    [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Bolsa" },
    [33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Caso" },
    [34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Grande bolsa" },
    [35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Bonsaw" },
    [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertilizante" },
    [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Bolsa de compras" },
    [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Frasco" },
    [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Boneca de pano" }, 
  },

  ["Geral 4"] = {
    [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Fictício" },
    [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Relógio de ovo" },
    [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
    [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
    [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
    [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Saco de ração" },
    [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Espanador de chão" },
    [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Cesto de frutas" },
    [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Espanador" },
    [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Uvas" },
    [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Relógio do hotel" },
    [12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Caso Ídolo" },
    [13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Jóias" },
    [14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Jóias" },
    [15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Jóias" },
    [16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Jóias" },
    [17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jóias" },
    [18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Jóias" },
    [19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Jóias" },
    [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Bandeja de exibição" },
    [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Tela verde" },
    [29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Bolsa" },
    [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
    [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Teclado 1" },
    [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Teclado 2" },
    [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Mala 1" },
    [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Mala 2" },
    [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
    [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Framboesa limpa" },
    [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Saco de papel" },
    [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Sacolas de compras" },
    [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Sacolas de compras 2" },
    [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Comida de Yoga 1" },
    [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Comida de Yoga 2" },
    [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Comida de Yoga 3" },
    [43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Certo" },
    [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "Bola de futebol" },
    [45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Assista 1" },
    [46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Assista 2" },
    [47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Assista 3" },
    [48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Assista 4" },
    [49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Assista 5" },
    [51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Assista 6" },
  },

  ["Pequena"] = {
    [1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Gato Figo" },
    [2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Figo Palhaço" },
    [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Autenticação de Figo" },
    [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Figo Fêmea" },
    [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Figo Flamenco" },
    [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Garota Figo" },
    [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Figo Palhaço" },
    [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
    [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Pilares de Figo" },
    [10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Bule" },
    [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Escultura 1" },
    [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Escultura 2" },
    [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Escultura 3" },
    [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Escultura 4" },
    [15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skate" },
    [16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Bloco de desenho" },
    [17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Tecidos" },
    [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Cesta" },
    [19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Caixa" },
    [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Almofada 1" },
    [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Almofada 2" },
    [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Almofada 3" },
    [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Almofada 4" },
    [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Almofada 5" },
    [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Almofada 6" },
    [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "fruteira" },
    [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Aparador" },
    [28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Ídolo 1" },
    [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["name"] = "Punhos" },
    [30] = { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Boas vibrações" },
    [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Boas vibrações 2" },
    [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Boas vibrações 3" },
    [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "Boas vibrações 4" },
    [34] = { ["object"] = "v_res_d_lube", ["price"] = 100, ["name"] = "Lubrificante" },
    [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Bandeja de mesa" },
    [36] = { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "Caixa de arquivos" },
  },

  ["Armazenamento"] = {
    [1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Armário Grande" },
    [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Penteadeira" },
    [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Unidade Lateral" },
    [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Unidade Lateral" },
    [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Unidade Lateral" },
    [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Unidade de Cama" },
    [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Unidade de TV" },
    [8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Unidade de Cômoda" },
    [9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Unidade de fundo" },
    [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Unidade de console" },
    [11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Armário" },
    [12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Unidade de Peito" },
    [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Unidade de pedreiro" },
    [14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Unidade de Gabinete" },
    [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Unidade Lateral" },
    [16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Unidade de mesa" },
    [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Unidade Lateral" },
    [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Unidade Lateral 2" },
    [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Unidade de livro" },
    [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Unidade de Caixa" },
    [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Unidade de armazenamento" },
    [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Armário" },
    [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Unidade de Madeira" },
    [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Saco de feijão 1" },
    [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Mil Crate 1" },
    [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Mil Crate 2" },
    [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Seguro" },
  },

  ["Eletrônicos"] = {
    [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Geladeira Antiga" },
    [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Palestrante" },
    [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Base de alto-falante" },
    [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Relógio de cabeceira" },
    [5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Telefone" },
    [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Ventilador de Torre" },
    [7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fã" },
    [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Tela grande" },
    [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
    [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Misturador" },
    [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
    [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Computador portátil" },
    [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },
    [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "Televisão de ecrã plano" },
    [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "aparelho de televisão 1" },
    [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "aparelho de televisão 2" },
    [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1000, ["name"] = "aparelho de televisão 3" },
    [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Juke-box" },
    [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Ventilador de chão" },
    [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "Teclado de computador" },
    [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Máquina de café" },
  },


  ["Iluminação"] = {
    [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Lâmpada de mesa" },
    [2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Lâmpada de mesa" },
    [3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Lâmpada AA" },
    [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Lâmpada 1" },
    [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Luminária de piso" },
    [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lâmpada 2" },
    [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Lâmpada de mesa" },
    [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Candeeiro de Mesa 2" },
    [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Lâmpada de cama" },
    [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Lâmpada de Língua de Planta" },
    [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Candeeiro de Mesa 3" },
    [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Suporte de lâmpada" },
    [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Suporte de lâmpada 2" },
    [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Candeeiro de Mesa 4" },
    [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Ventilador de luz" },
    [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Lâmpada alta" },
    [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Luz de parede" },
    [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "Grampo g" },
    [19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Luz piscando" },
    [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Luz de parede lateral" },
    [21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Luz de teste" },
  },


  ["Mesas"] = {
    [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Mesa de centro 1" },
    [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Mesa redonda" },
    [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Mesa Lateral Pequena" },
    [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Tabela A" },
    [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Tabela B" },
    [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Tabela C" },
    [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Mesa de jantar" },
    [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Mesa de centro 2" },
    [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Mesa baixa" },
    [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Cama-mesa" },
    [11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Mesa" },
    [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Mesa de apoio" },
    [13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Tabela de console" },
    [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Mesa de jantar 2" },
    [15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Mesa do console H" },
    [16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Banco?" },
    [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Mesa aparador" },
    [18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "mesa 2" },
    [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Mesa de TV" },
    [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Mesa de TV alta" },
    [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Mesa de centro mediterrânea" },
    [22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Com Secretária" },
    [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Mesa de Iate 1" },
    [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Mesa de Iate 2" },
    [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Mesa de Iate 3" },
    [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "Tabela CSR" },
    [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 100, ["name"] = "Mesa de jantar c cadeiras" },
  },

  ["Plantas"] = {
    [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Planta Fib" },
    [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Plantar bomba" },    
    [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Plantar flores" }, 
    [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Planta chinesa" }, 
    [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Plantar Banana" }, 
    [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Plantar Palmeira" },  
    [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Planta Palma 2" },  
    [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Urna de Plantas" },  
    [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Borracha vegetal" }, 
    [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Plantar" }, 
    [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Plantar árvore" }, 
    [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Plantador" }, 
    [13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flores" },
    [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flores 1" },
    [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flores 2" },
    [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 100, ["name"] = "Flores 3" },
    [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Flores 4" },
    [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Árvore de Natal" },
  },

  ["Cozinha"] = {
    [1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Arruela 1" },
    [2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Arruela 2" },
    [3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Arruela 3" },
    [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Cesto de Lavar" },
    [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Geladeira 1" },
    [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Geladeira 2" },
    [7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Geladeira 3" },
    [8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Geladeira 4" },
    [9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Fogão" },
    [10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microondas 1" },
    [11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Microondas 2" },
    [12] = { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Wok" },
    [13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Prato de Bolo" },
    [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Tábua de cortar" },
    [15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Utensílios" },
    [16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pilão" },
    [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "Rolo de Papel 1" },
    [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "Rolo de Papel 2" },
    [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Pote 1" },
    [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Pote 2" },
    [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Pote 3" },
    [22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Pote 4" },
    [23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Pote 5" },
    [24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Pote 6" },
    [25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Pote 7" },
    [26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Prateleira" },
    [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Espremedor" },
  },


  ["Banheiro"] = {
    [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Banheiro 1" },
    [2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Banheiro 2" },
    [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Banheiro 3" },
    [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Pia 1" },
    [5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Pia 2" },
    [6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Pia 3" },
    [7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Pia 4" },
    [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Saboneteira" },
    [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Rack de Chuveiro" },
    [10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Secador de mãos 1" },
    [11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Secador de mãos 2" },
    [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Toalheiro 1" },
    [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Toalheiro 2" },
    [14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Toalha 1" },
    [15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Toalha 2" },
    [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Toalha 3" },
    [17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Banho" },
    [18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Afundar" },
  },

  ["Médico"] = {
    [1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barril" },
    [2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Caixa de macaco" },
    [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Caixote de Macaco Grande" },
    [4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Cama 1" },
    [5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Cama 2" },
    [6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Cama-mesa" },
    [7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Banco 1" },
    [8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Banco 2" },
    [9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Centro de bancada" },
    [10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Conjunto de banco" },
    [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Mesa grande" },
    [12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Caixa" },
    [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrífuga" },
    [14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Resfriador" },
    [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
    [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Mesa de autópsia" },
    [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Caixa" },
    [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Carrinho" },
    [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Química" },
    [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "Tabela BLM" },
    [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "Caixa de arquivos" },
    [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "Cabine de arquivo" },
    [23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Mangueira" },
    [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Armário Grande" },
    [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Caixa de luz" },
    [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Medstool" },
    [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Mini geladeira" },
    [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Toalhas de papel" },
    [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Fotocópia" },
    [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "Suporte de TV" },
    [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Unidade de parede" },
    [32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Luz do exame" },
    [33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Tanque de gás" },
    [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Verificação de materiais perigosos" },
    [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Parede principal" },
    [36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Assentos" },
    [37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Mesa Hospitalar" },
    [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Porta-luvas" },
    [39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Lixeira" },
    [40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Oscilador" },
    [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Pacote de Saúde" },
  }
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
  dropdowntable[category] = {}

  for o,k in pairs(v) do

    local hash = GetHashKey(k.object)
    hashtable[hash] = k
  
    local id = k.object or "none"
    local name = k.name or "none"
    local price = k.price or 9999

    lookuptable[id] = k

    table.insert(dropdowntable[category],{id = id,name = name,price = price})
  end 
end 

for k,v in pairs(furni.objects) do
  for k,v in pairs(v) do
    v.id = v.object
  end
end



mLibs = exports["meta_libs"]